[[session]]
name = "Dotfiles âš™ï¸"
path = "~/.dotfiles"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Home ğŸ "
path = "~"

[[session]]
name = "Evo ğŸª´"
path = "~/Documents/EVO/js-clients/"
startup_script = "~/.config/sesh/scripts/evo"

[[session]]
name = "Diesel ğŸ¶"
path = "~/Documents/Diesel/"

[[session]]
name = "Dev ğŸ’»"
path = "~/Documents/dev/"
startup_command = "l"
