[[session]]
name = "âš™ï¸ Dotfiles"
path = "~/.dotfiles"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "ğŸ Home"
path = "~"

[[session]]
name = "ğŸ¥¥Ela" 
path = "~/Documents/Ela"
# startup_script = "~/.config/sesh/scripts/evo"

[[session]]
name = "ğŸª´Evo"
path = "~/Documents/EVO/js-clients/"
startup_script = "~/.config/sesh/scripts/evo"

[[session]]
name = "ğŸ¶Diesel"
path = "~/Documents/Diesel/"

[[session]]
name = "ğŸ’»Dev"
path = "~/Documents/dev/"
startup_command = "l"

[[session]]
name = "ğŸ–¥ Desktop"
path = "~/Desktop/"
